name: Bug 报告
description: 报告 iWeather 中的 bug 或异常行为
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你花时间报告 bug！请填写以下部分，以便我们复现和修复问题。

  - type: input
    id: version
    attributes:
      label: iWeather 版本
      description: "在设置或标题栏中找到（例如 0.4.6）"
      placeholder: "0.4.6"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 操作系统
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Windows 11
        - Windows 10
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (Arch)
        - Linux (其他)
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: 系统版本
      description: "例如 macOS 15.3, Windows 11 24H2, Ubuntu 24.04"
      placeholder: "macOS 15.3"
    validations:
      required: true

  - type: dropdown
    id: ai_provider
    attributes:
      label: AI 提供商
      description: 你使用的是哪个 AI 提供商/连接？
      options:
        - Anthropic API (直连)
        - Anthropic API (自定义端点)
        - OpenAI / Codex
        - Copilot (GitHub)
        - 其他
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: 模型
      description: "你使用的是哪个模型？（例如 Claude Opus 4.6, GPT-4.1）"
      placeholder: "Claude Opus 4.6"

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 清晰描述 bug 是什么。
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      description: 复现行为的分步说明。
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 你期望发生什么？
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 实际行为
      description: 实际发生了什么？
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 截图 / 屏幕录制
      description: |
        对于 **UI 问题**，请附上显示问题的截图或屏幕录制。
        你可以直接将图片/视频拖放到此字段中。

  - type: textarea
    id: logs
    attributes:
      label: 调试日志
      description: |
        对于 **非 UI 问题**（崩溃、错误、连接问题），请附上调试会话的相关日志。

        使用 `-- --debug` 启动应用并复现问题。有关各平台的命令和日志文件位置，请参阅 README 中的故障排除部分。
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: 附加信息
      description: 关于问题的任何其他背景信息（使用的 MCP 数据源、工作区配置等）
